/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeluguRouteImport } from './routes/telugu'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as SpellingRouteImport } from './routes/spelling'
import { Route as SolarsystemRouteImport } from './routes/solarsystem'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShapesRouteImport } from './routes/shapes'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayzoneRouteImport } from './routes/playzone'
import { Route as NumbersRouteImport } from './routes/numbers'
import { Route as MathRouteImport } from './routes/math'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AlphabetsRouteImport } from './routes/alphabets'
import { Route as IndexRouteImport } from './routes/index'

const TeluguRoute = TeluguRouteImport.update({
  id: '/telugu',
  path: '/telugu',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const SpellingRoute = SpellingRouteImport.update({
  id: '/spelling',
  path: '/spelling',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarsystemRoute = SolarsystemRouteImport.update({
  id: '/solarsystem',
  path: '/solarsystem',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShapesRoute = ShapesRouteImport.update({
  id: '/shapes',
  path: '/shapes',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayzoneRoute = PlayzoneRouteImport.update({
  id: '/playzone',
  path: '/playzone',
  getParentRoute: () => rootRouteImport,
} as any)
const NumbersRoute = NumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const MathRoute = MathRouteImport.update({
  id: '/math',
  path: '/math',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AlphabetsRoute = AlphabetsRouteImport.update({
  id: '/alphabets',
  path: '/alphabets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alphabets': typeof AlphabetsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/math': typeof MathRoute
  '/numbers': typeof NumbersRoute
  '/playzone': typeof PlayzoneRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/shapes': typeof ShapesRoute
  '/signup': typeof SignupRoute
  '/solarsystem': typeof SolarsystemRoute
  '/spelling': typeof SpellingRoute
  '/tables': typeof TablesRoute
  '/telugu': typeof TeluguRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alphabets': typeof AlphabetsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/math': typeof MathRoute
  '/numbers': typeof NumbersRoute
  '/playzone': typeof PlayzoneRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/shapes': typeof ShapesRoute
  '/signup': typeof SignupRoute
  '/solarsystem': typeof SolarsystemRoute
  '/spelling': typeof SpellingRoute
  '/tables': typeof TablesRoute
  '/telugu': typeof TeluguRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alphabets': typeof AlphabetsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/math': typeof MathRoute
  '/numbers': typeof NumbersRoute
  '/playzone': typeof PlayzoneRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/shapes': typeof ShapesRoute
  '/signup': typeof SignupRoute
  '/solarsystem': typeof SolarsystemRoute
  '/spelling': typeof SpellingRoute
  '/tables': typeof TablesRoute
  '/telugu': typeof TeluguRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alphabets'
    | '/dashboard'
    | '/login'
    | '/math'
    | '/numbers'
    | '/playzone'
    | '/profile'
    | '/rewards'
    | '/shapes'
    | '/signup'
    | '/solarsystem'
    | '/spelling'
    | '/tables'
    | '/telugu'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alphabets'
    | '/dashboard'
    | '/login'
    | '/math'
    | '/numbers'
    | '/playzone'
    | '/profile'
    | '/rewards'
    | '/shapes'
    | '/signup'
    | '/solarsystem'
    | '/spelling'
    | '/tables'
    | '/telugu'
  id:
    | '__root__'
    | '/'
    | '/alphabets'
    | '/dashboard'
    | '/login'
    | '/math'
    | '/numbers'
    | '/playzone'
    | '/profile'
    | '/rewards'
    | '/shapes'
    | '/signup'
    | '/solarsystem'
    | '/spelling'
    | '/tables'
    | '/telugu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlphabetsRoute: typeof AlphabetsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MathRoute: typeof MathRoute
  NumbersRoute: typeof NumbersRoute
  PlayzoneRoute: typeof PlayzoneRoute
  ProfileRoute: typeof ProfileRoute
  RewardsRoute: typeof RewardsRoute
  ShapesRoute: typeof ShapesRoute
  SignupRoute: typeof SignupRoute
  SolarsystemRoute: typeof SolarsystemRoute
  SpellingRoute: typeof SpellingRoute
  TablesRoute: typeof TablesRoute
  TeluguRoute: typeof TeluguRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/telugu': {
      id: '/telugu'
      path: '/telugu'
      fullPath: '/telugu'
      preLoaderRoute: typeof TeluguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spelling': {
      id: '/spelling'
      path: '/spelling'
      fullPath: '/spelling'
      preLoaderRoute: typeof SpellingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solarsystem': {
      id: '/solarsystem'
      path: '/solarsystem'
      fullPath: '/solarsystem'
      preLoaderRoute: typeof SolarsystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shapes': {
      id: '/shapes'
      path: '/shapes'
      fullPath: '/shapes'
      preLoaderRoute: typeof ShapesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playzone': {
      id: '/playzone'
      path: '/playzone'
      fullPath: '/playzone'
      preLoaderRoute: typeof PlayzoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numbers': {
      id: '/numbers'
      path: '/numbers'
      fullPath: '/numbers'
      preLoaderRoute: typeof NumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math': {
      id: '/math'
      path: '/math'
      fullPath: '/math'
      preLoaderRoute: typeof MathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alphabets': {
      id: '/alphabets'
      path: '/alphabets'
      fullPath: '/alphabets'
      preLoaderRoute: typeof AlphabetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlphabetsRoute: AlphabetsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MathRoute: MathRoute,
  NumbersRoute: NumbersRoute,
  PlayzoneRoute: PlayzoneRoute,
  ProfileRoute: ProfileRoute,
  RewardsRoute: RewardsRoute,
  ShapesRoute: ShapesRoute,
  SignupRoute: SignupRoute,
  SolarsystemRoute: SolarsystemRoute,
  SpellingRoute: SpellingRoute,
  TablesRoute: TablesRoute,
  TeluguRoute: TeluguRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
